# Generated by Django 4.1.6 on 2023-03-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
